branch-defaults:
  development:
    environment: DiegoUdacity-Project2-dev
    group_suffix: null
global:
  application_name: DiegoUdacity-Project2
  branch: null
  default_ec2_keyname: udacity-basic
  default_platform: Node.js
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
deploy:
    artifact: ./www/Archive.zip